/**
 * lib/side-effects.ts 规则表：被打断的工具可能留下什么半截副作用。每一行都是一条规则的正例或反例；
 * 最怕的是把对外 / 不可逆的判成「可以重跑」，所以 external 的反例（只读的同名命令）也逐条列出。
 */
import { describe, expect, test } from "bun:test";
import { bashCommandOf, classifyBash, classifyTool, type SideEffect } from "../src/lib/side-effects.js";

const BASH: [string, SideEffect][] = [
  // none：只读
  ["git status", "none"],
  ["git log --oneline -5", "none"],
  ["git diff HEAD~1 -- src/bridge.ts", "none"],
  ["git -C /tmp/wt status", "none"],
  ["git branch --show-current", "none"],
  ["git tag", "none"],
  ["git tag -l 'v2.*'", "none"],
  ["ls -la && cat package.json", "none"],
  ["grep -rn preempt src | head -20", "none"],
  ["sed -n 1,40p src/bridge.ts", "none"],
  ["find src -name '*.ts'", "none"],
  ["bun test tests/x.test.ts", "none"],
  ["bun run check", "none"],
  ["bunx tsc --noEmit -p .", "none"],
  ["gh pr view 129", "none"],
  ["gh pr list --state open", "none"],
  ["gh release view v2.30.0", "none"],
  ["gh api repos/o/r/pulls", "none"],
  ["curl -s http://127.0.0.1:3847/stats", "none"],
  ["bun src/manager.ts list", "none"],
  ["bun src/manager.ts doctor --json", "none"],
  ["bun src/manager.ts peer-http-list", "none"],
  ["launchctl list | grep claudestra", "none"],
  ["tmux capture-pane -t master:x -p", "none"],
  ["cd web && ls", "none"],
  ["echo hi 2>&1", "none"],
  ["ls > /dev/null", "none"],
  // idempotent：可以直接重跑
  ["bun src/manager.ts web-release deploy --ref main", "idempotent"],
  ["npm run build", "idempotent"],
  ["bun run build:web", "idempotent"],
  ["git fetch origin", "idempotent"],
  ["git push origin task/t13a", "idempotent"],
  ["git push -u origin HEAD", "idempotent"],
  ["launchctl kickstart -k gui/501/com.claudestra.bridge", "idempotent"],
  ["bun install", "idempotent"],
  ["mkdir -p /tmp/x", "idempotent"],
  ["git add src/lib/a.ts src/lib/b.ts", "idempotent"],
  // check_first：先核对再重来
  ["bun src/manager.ts create t9 /tmp/x", "check_first"],
  ["bun src/manager.ts kill agent-t3", "check_first"],
  ["bun src/manager.ts rename a b", "check_first"],
  ["bun src/manager.ts restart agent-x", "check_first"],
  ["bun src/manager.ts update", "check_first"],
  ["claudestra install-cli", "check_first"],
  ["launchctl bootout gui/501/com.claudestra.bridge", "check_first"],
  ["launchctl bootstrap gui/501 ~/Library/LaunchAgents/x.plist", "check_first"],
  ["gh pr merge 129 --squash", "check_first"],
  ["git commit -m 'x'", "check_first"],
  ["git rebase origin/main", "check_first"],
  ["git stash push -m tag", "check_first"],
  ["sed -i '' 's/a/b/' f.ts", "check_first"],
  ["find . -name '*.tmp' -delete", "check_first"],
  ["echo hi > out.txt", "check_first"],
  ["python3 scripts/migrate.py", "check_first"],
  ["./deploy.sh", "check_first"],
  ["ssh tokyo 'systemctl restart relay'", "check_first"],
  ["rm -rf /tmp/wt-old", "check_first"],
  ["git status && git commit -am x", "check_first"],
  // external：对外 / 不可逆
  ["git tag v2.31.0", "external"],
  ["git tag -a v2.31.0 -m x", "external"],
  ["git push --force origin main", "external"],
  ["git push -f origin main", "external"],
  ["git push --force-with-lease origin x", "external"],
  ["git push origin --delete task/old", "external"],
  ["git push origin :task/old", "external"],
  ["git push origin v2.31.0", "external"],
  ["git push --tags", "external"],
  ["gh release create v2.31.0 --notes x", "external"],
  ["gh pr create --title x --body y", "external"],
  ["gh pr comment 12 --body hi", "external"],
  ["gh api -X POST repos/o/r/issues -f title=x", "external"],
  ["curl -X POST https://api.example.com/orders -d '{}'", "external"],
  ["curl -XDELETE https://api.example.com/orders/1", "external"],
  ["curl https://x.example -d a=1", "external"],
  ["npm publish", "external"],
  ["bun src/manager.ts peer-invite-new --agents a", "external"],
  ["bun src/manager.ts token-add web --agents '*'", "external"],
  ["git fetch && git push --force origin main", "external"],
  // 对抗式审查（#148 第 2 轮 P2-10）列出的漏判
  ["wget --post-data 'a=1' https://x.example/api", "external"],
  ["wget --method=DELETE https://x.example/api/1", "external"],
  ["http POST https://x.example/orders qty=1", "external"],
  ["http https://x.example/orders qty:=1", "external"],
  ["curl --json '{\"a\":1}' https://x.example/api", "external"],
  ["curl --request=POST https://x.example/api", "external"],
  ["curl -X POST https://x.example/api", "external"],
  ["kubectl delete pod web-0", "external"],
  ["kubectl apply -f deploy.yaml", "external"],
  ["aws s3 rm s3://bucket/key", "external"],
  ["aws ec2 terminate-instances --instance-ids i-1", "external"],
  ["gcloud run deploy api", "external"],
  ["terraform apply -auto-approve", "external"],
  ["helm upgrade web ./chart", "external"],
  // 同家族的只读命令不能被连带判成对外
  ["curl -X GET https://x.example/api", "none"],
  ["curl --request=GET https://x.example/api", "none"],
  ["http https://x.example/orders", "none"],
  ["wget https://x.example/file.tar.gz", "none"],
  ["kubectl get pods -A", "none"],
  ["kubectl logs web-0", "none"],
  ["aws s3 ls s3://bucket", "none"],
  ["aws ec2 describe-instances", "none"],
  ["terraform plan", "none"],
  ["helm status web", "none"],
  // Workflow 审查补充：短选项连写、后台 &、--follow-tags、fd -x
  ["curl -s -d@order.json https://x.example/api", "external"],
  ["curl -sX POST https://x.example/api", "external"],
  ["curl -sXPOST https://x.example/api", "external"],
  ["sleep 2 & curl -X POST https://x.example/api", "external"],
  ["git push -fu origin main", "external"],
  ["git push --follow-tags", "external"],
  ["fd -x rm {}", "check_first"],
  ["curl -sSL https://x.example/install.sh", "none"],
  ["echo hi 2>&1 | grep hi", "none"],
  ["git push -u origin feature", "idempotent"],
  // 对抗式第 3 轮（P1-C）：云命令只放行读动词，其余一律对外
  ["aws s3 rb s3://prod-bucket --force", "external"],
  ["aws s3 mb s3://new", "external"],
  ["aws dynamodb batch-write-item --request-items file://x.json", "external"],
  ["aws dynamodb transact-write-items --transact-items file://x.json", "external"],
  ["aws route53 change-resource-record-sets --hosted-zone-id Z --change-batch file://c.json", "external"],
  ["aws ec2 authorize-security-group-ingress --group-id sg-1 --port 22", "external"],
  ["aws ec2 revoke-security-group-ingress --group-id sg-1", "external"],
  ["aws lambda add-permission --function-name f", "external"],
  ["aws ecs execute-command --cluster c", "external"],
  ["gcloud container clusters resize c --num-nodes 0", "external"],
  ["az vm deallocate -g rg -n vm", "external"],
  ["gcloud compute instances delete list", "external"],
  ["aws sts get-caller-identity", "none"],
  ["aws dynamodb get-item --table-name t --key k", "none"],
  ["gcloud compute instances list", "none"],
  ["gcloud container clusters describe c", "none"],
  ["az vm show -g rg -n vm", "none"],
  ["az account show", "none"],
  ["terraform force-unlock 123", "external"],
  ["terraform refresh", "external"],
  ["terraform state list", "none"],
  ["terraform output -json", "none"],
  ["terraform init", "idempotent"],
  // 命令替换 / 反引号 / 进程替换里的命令单独分类
  ['echo "order: $(curl -s -X POST https://api/order -d @o.json)"', "external"],
  ["echo `curl -X POST https://x`", "external"],
  ["diff <(curl -s -X DELETE https://x/1) a.txt", "external"],
  ['echo "$(date)"', "none"],
  ["echo $((1 + 2))", "none"],
  ["git push origin $(git branch --show-current)", "idempotent"],
  ["echo `unterminated", "check_first"],
  // --method= / --in-place / stdin 请求体 / 引号里的方法 / 续行
  ["gh api --method=DELETE repos/o/r/git/refs/heads/x", "external"],
  ["gh api --method=PUT repos/o/r/pulls/1/merge", "external"],
  ["gh api -XDELETE repos/o/r/git/refs/heads/x", "external"],
  ["gh api -X GET search/issues -f q=x", "none"],
  ["gh workflow run deploy.yml", "external"],
  ["gh repo delete o/r --yes", "external"],
  ["sed --in-place s/a/b/ f.txt", "check_first"],
  ["sed -ni 's/a/b/p' f.txt", "check_first"],
  ["http https://api/order < order.json", "external"],
  ["http POST https://api/order <<< '{}'", "external"],
  ['curl -X"POST" https://x', "external"],
  ["curl https://api/order \\\n  -H 'Content-Type: application/json' \\\n  -d @order.json", "external"],
  ["cat order.json | curl -d @- https://api", "external"],
  // wf2 classify-merge-2：httpie 管道喂请求体、带值选项排在方法前、--raw；查询参数 q==x 仍是读
  ["cat order.json | http https://api/order", "external"],
  ["echo '{}' | xh https://api/order", "external"],
  ["cat q.json | http --ignore-stdin https://api/items", "none"],
  ["http -a user:pass DELETE https://api/items/1", "external"],
  ["http --timeout 5 DELETE https://api/items/1", "external"],
  ["xh -A bearer -a TOKEN delete https://api/items/1", "external"],
  ["http --raw='{\"a\":1}' https://api/order", "external"],
  ["http https://api/items q==x", "none"],
  // classify-merge-3：gcloud / az 按命令路径判，资源名、选项值里的读词不算；kubectl auth / config 不是整组只读
  ["gcloud scheduler jobs run get-prices-job --location us-central1", "external"],
  ["gcloud functions call list-orders --data '{}'", "external"],
  ["gcloud workflows run show-report", "external"],
  ["gcloud pubsub topics publish orders --message list", "external"],
  ["gcloud sql instances patch db --tier db-f1-micro", "external"],
  ["az functionapp deployment source config-zip -g rg -n get-user-fn --src fn.zip", "external"],
  ["az vm run-command invoke -g rg -n vm --scripts ls", "external"],
  ["gcloud compute instances list", "none"],
  ["gcloud run services list", "none"],
  ["gcloud projects get-iam-policy p", "none"],
  ["az vm show -g rg -n vm", "none"],
  ["kubectl auth reconcile -f rbac.yaml", "external"],
  ["kubectl auth can-i get pods", "none"],
  ["kubectl config use-context prod", "check_first"],
  ["kubectl config current-context", "none"],
  ["kubectl config view", "none"],
  // classify-merge-7：shell 结构、外壳、把命令当参数跑的
  ["for id in 1 2 3; do curl -X DELETE https://api/items/$id; done", "external"],
  ["if true; then kubectl delete ns prod; fi", "external"],
  ["{ curl -X POST https://x; }", "external"],
  ["cat ids | xargs -I{} curl -X DELETE https://api/{}", "external"],
  ["cat ids | xargs -n 1 -P 4 curl -X DELETE", "external"],
  ["bash -c 'kubectl delete ns prod'", "external"],
  ["watch -n 5 kubectl get pods", "none"],
  ["nice -n 10 aws s3 rm s3://b --recursive", "external"],
  ["sudo -u deploy kubectl apply -f x.yaml", "external"],
  ["find . -name '*.log' | xargs grep ERROR", "none"],
  // classify-merge-7：发布 / 部署 / 数据库客户端
  ["npm unpublish pkg@1.0.0", "external"],
  ["npm dist-tag add pkg@1.0.0 latest", "external"],
  ["yarn npm publish", "external"],
  ["docker image push reg/x:1", "external"],
  ["docker buildx build --push -t reg/x .", "external"],
  ["twine upload dist/*", "external"],
  ["vercel --prod", "external"],
  ["fly deploy", "external"],
  ["wrangler deploy", "external"],
  ["firebase deploy", "external"],
  ["pulumi up --yes", "external"],
  ["gh secret set TOKEN --body x", "external"],
  ["gh gist create --public a.txt", "external"],
  ["gh run cancel 123", "external"],
  ["gh -R o/r pr create --fill", "external"],
  ["gh -R o/r pr view 1", "none"],
  ["git --git-dir=.git push --force origin main", "external"],
  ["git --no-pager log -5", "none"],
  ['psql "$PROD_URL" -c "DROP TABLE users"', "external"],
  ['psql "$URL" -c "select 1"', "check_first"],
  ["redis-cli -h prod FLUSHALL", "external"],
  ["wget -qO- --header=X:y --method=POST https://x", "external"],
  ["fd --exec=rm x", "check_first"],
  ["git reflog expire --expire=now --all", "check_first"],
  ["git reflog", "none"],
  ["git reflog show main", "none"],
  ["git remote set-url origin git@x:y", "check_first"],
  ["git remote remove origin", "check_first"],
  ["git remote -v", "none"],
  ["git remote", "none"],
  ["git config --unset user.name", "check_first"],
  ["git config user.name foo", "check_first"],
  ["git config user.name", "none"],
  ["git config --get user.name", "none"],
  ["git push --force-if-includes origin main", "external"],
  ["sort -o data.txt data.txt", "check_first"],
  ["sort -u data.txt", "none"],
  ["tsc", "idempotent"],
  ["tsc --noEmit", "none"],
  ["npm run lint -- --fix", "check_first"],
  ["bunx prettier --write .", "check_first"],
  // wf2 classify-merge-5：其它判 none 的写法
  ["echo k 1> ~/.ssh/authorized_keys", "check_first"],
  ["echo k 1>&2", "none"],
  ["ls 2> err.log", "none"],
  ["curl -K req.cfg https://x", "check_first"],
  ["curl -sQ 'DELE f' ftp://h/", "check_first"],
  ["curl -X PURGE https://x", "external"],
  ["curl -XGET https://x", "none"],
  ["curl -I -X HEAD https://x", "none"],
  ["uniq in out", "check_first"],
  ["uniq -c in", "none"],
  ["uniq -f 1 in", "none"],
  ["tree -o out", "check_first"],
  ["tree -L 2", "none"],
  ["sudo hostname prod-db", "check_first"],
  ["hostname -f", "none"],
  ["sudo date -s 2020-01-01", "check_first"],
  ["date +%s", "none"],
  ["find . -fprint out", "check_first"],
  ["find . -fprintf out %p", "check_first"],
  ["find . -fls out", "check_first"],
  ["find . -okdir rm {} ;", "check_first"],
  ["fd -HX rm", "check_first"],
  ["fd -H x", "none"],
  ["bun test -u", "check_first"],
  ["bun test --update-snapshots", "check_first"],
  // wf2 classify-merge-6：全局选项写在动词前、不以 get / list 开头的读
  ["kubectl -n kube-system get pods", "none"],
  ["kubectl --context=prod get pods", "none"],
  ["kubectl -n prod delete pod x", "external"],
  ["helm -n prod list", "none"],
  ["helm -n prod uninstall x", "external"],
  ["terraform -chdir=infra plan", "none"],
  ["terraform -chdir=infra apply", "external"],
  ["aws --profile prod s3 ls", "none"],
  ["aws --profile prod s3 rm s3://b/k", "external"],
  ["aws --region us-east-1 ec2 describe-instances", "none"],
  ["aws logs tail /x --follow", "none"],
  ["aws logs filter-log-events --log-group-name x", "none"],
  ["aws dynamodb query --table-name t", "none"],
  ["aws dynamodb scan --table-name t", "none"],
  ["aws dynamodb put-item --table-name t", "external"],
  ["aws s3 presign s3://b/k", "none"],
  ["gcloud auth print-access-token", "none"],
  ["gcloud secrets versions access latest --secret=x", "none"],
  ["gcloud --project p compute instances list", "none"],
  ["gcloud --project p compute instances delete vm", "external"],
  ["gh api graphql -f query='query{viewer{login}}'", "none"],
  ["gh api graphql -f query='{ viewer { login } }'", "none"],
  ["gh api graphql -f query='mutation { addStar(input:{}) { clientMutationId } }'", "external"],
  ["gh api graphql -F query=@q.graphql", "external"],
];

describe("classifyBash 规则表", () => {
  for (const [cmd, kind] of BASH) {
    test(`${kind.padEnd(11)} ${cmd}`, () => {
      expect(classifyBash(cmd).kind).toBe(kind);
    });
  }

  test("空命令 / 认不出的一律 check_first，并给出核对建议", () => {
    expect(classifyBash("").kind).toBe("check_first");
    const v = classifyBash("frobnicate --all");
    expect(v.kind).toBe("check_first");
    expect(v.hint).toBeTruthy();
  });

  test("项目登记的对外关键字（交易脚本）→ external", () => {
    expect(classifyBash("python3 place_order.py --qty 10", ["place_order"]).kind).toBe("external");
    expect(classifyBash("python3 report.py", ["place_order"]).kind).toBe("check_first");
  });

  test("部署带「可以直接重跑」的理由，gh pr merge 带核对建议", () => {
    expect(classifyBash("bun src/manager.ts web-release deploy").hint).toContain("原子切换");
    expect(classifyBash("gh pr merge 1").hint).toContain("gh pr view");
  });
});

describe("classifyTool：非 Bash 工具", () => {
  const cases: [string, SideEffect, { command?: string; target?: string }?][] = [
    ["Read", "none"],
    ["Grep", "none"],
    ["WebFetch", "none"],
    ["TaskCreate", "idempotent"],
    ["Edit", "check_first"],
    ["Write", "check_first"],
    ["Agent", "check_first"],
    ["mcp__mem0__memory_search", "none"],
    ["mcp__mem0__memory_write", "check_first"],
    ["mcp__playwright__browser_snapshot", "none"],
    ["mcp__playwright__browser_click", "check_first"],
    ["mcp__slack__post_message", "external"],
    ["mcp__github__create_pull_request", "external"],
    ["mcp__gmail__send_email", "external"],
    ["mcp__slack__list_channels", "none"],
    // 对抗式第 3 轮：数据库的 query / execute 可能是写语句；下单 / 退款不管哪个服务都算对外
    ["mcp__db__query", "check_first"],
    ["mcp__postgres__query", "check_first"],
    ["mcp__db__execute_sql", "check_first"],
    ["mcp__supabase__apply_migration", "check_first"],
    ["mcp__binance__place_order", "external"],
    ["mcp__exchange__cancel_order", "external"],
    ["mcp__trading__buy", "external"],
    ["mcp__trading__submit_order", "external"],
    ["mcp__stripe__refund", "external"],
    ["mcp__github__merge_pull_request", "external"],
    ["mcp__gmail__search_threads", "none"],
    ["mcp__foo__get_or_create", "check_first"],
    ["mcp__github__get_pull_request", "none"],
    ["mcp__claudestra__reply", "check_first"],
    ["mcp__claudestra__send_to_agent", "check_first", { target: "agent-codex" }],
    ["mcp__claudestra__send_to_agent", "external", { target: "future_data@ahh" }],
    ["send_to_agent", "external", { target: "peer:ahh.x" }],
    ["SomethingNew", "check_first"],
    // wf2 classify-merge-4：服务名不在 DB 表里、但工具名像在跑语句的；写词补全
    ["mcp__cloudflare__d1_database_query", "check_first"],
    ["mcp__cloudflare-bindings__d1_database_query", "check_first"],
    ["mcp__turso__query", "check_first"],
    ["mcp__redshift__query", "check_first"],
    ["mcp__oracle__query", "check_first"],
    ["mcp__foo__check_in", "check_first"],
    ["mcp__notes__get_or_insert", "check_first"],
    ["mcp__k8s__pods_exec_get", "check_first"],
    ["mcp__github__search_code", "none"],
    // wf2 classify-merge-6：以读动词开头的查订单 / 查记录不算下单
    ["mcp__binance__get_order", "none"],
    ["mcp__binance__get_order_status", "none"],
    ["mcp__stripe__list_payment_intents", "none"],
    ["mcp__binance__get_order_book", "none"],
    ["mcp__binance__get_transfer_history", "none"],
    ["mcp__binance__get_and_cancel_order", "external"],
    ["mcp__binance__place_order", "external"],
  ];
  for (const [name, kind, opts] of cases) {
    test(`${kind.padEnd(11)} ${name}${opts?.target ? ` → ${opts.target}` : ""}`, () => {
      expect(classifyTool(name, opts).kind).toBe(kind);
    });
  }

  test("Bash 走命令规则", () => {
    expect(classifyTool("Bash", { command: "git tag v1" }).kind).toBe("external");
  });
});

test("bashCommandOf：watcher 的 detail 是「描述 ─── 命令」，没有描述就只有命令", () => {
  expect(bashCommandOf("部署网页\n───\nbun src/manager.ts web-release deploy")).toBe("bun src/manager.ts web-release deploy");
  expect(bashCommandOf("git status")).toBe("git status");
});
